# Generated by Django 5.1.4 on 2025-01-06 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoursesCardModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_photo', models.ImageField(upload_to='card_photo/%Y/%m/%d')),
                ('course_name', models.CharField(blank=True, max_length=20)),
                ('short_description', models.CharField(blank=True, max_length=50)),
                ('long_description', models.TextField()),
                ('number_of_lecture', models.IntegerField()),
                ('time_of_course', models.TimeField()),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher_of_course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Course_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('number_of_video', models.IntegerField()),
                ('time_of_course', models.TimeField()),
                ('name_of_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.coursescardmodel')),
            ],
        ),
        migrations.AddField(
            model_name='coursescardmodel',
            name='teacher_of_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='courses.teacher_of_course'),
        ),
        migrations.CreateModel(
            name='VideosOfLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField()),
                ('name_of_course_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course_details')),
            ],
        ),
    ]
