# Generated by Django 5.1.4 on 2025-01-12 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course_details',
            old_name='number_of_video',
            new_name='time_of_video',
        ),
        migrations.RemoveField(
            model_name='course_details',
            name='time_of_course',
        ),
        migrations.AddField(
            model_name='course_details',
            name='url_file',
            field=models.URLField(blank=True, null=True, verbose_name='لینک دانلود'),
        ),
    ]
