# Generated by Django 5.1.4 on 2025-01-07 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_details_time_of_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_details',
            name='time_of_course',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='coursescardmodel',
            name='time_of_course',
            field=models.IntegerField(),
        ),
    ]
