# Generated by Django 5.1.4 on 2025-01-15 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('published', models.DateField(auto_now_add=True)),
                ('response', models.TextField()),
                ('level', models.CharField(choices=[('Easy', 'Easy'), ('Difficult', 'Difficult'), ('Intermediate', 'Intermediate')], default='Easy', max_length=15)),
                ('response_status', models.CharField(choices=[('Answered', 'Answered'), ('Not Answered', 'Not Answered')], default='Not Answered', max_length=15)),
            ],
        ),
    ]
